# -*- encoding: utf-8 -*-
"""
Training configuration for the diabetes two-stage model.
"""
import argparse
import torch


def opt_config():
    parser = argparse.ArgumentParser(description="Diabetes-two-stage")

    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu", help="device")
    parser.add_argument("--seed", type=int, default=42, help="random seed")
    parser.add_argument("--split_seed", type=int, default=0, help="random seed used only for dataset shuffling/splitting")
    parser.add_argument("--test_only", type=int, default=0, help="load model only without training")

    # Training
    parser.add_argument("--lr", type=float, default=5.0e-5, help="base learning rate")
    parser.add_argument("--optimizer", type=str, default="adamw", choices=["adam", "adamw"], help="optimizer type")
    parser.add_argument("--weight_decay", type=float, default=1e-4, help="weight decay")
    parser.add_argument("--batch_size", type=int, default=64, help="batch size")
    parser.add_argument("--epochs", type=int, default=1000, help="max training epochs")
    parser.add_argument("--mode", type=str, default="train", help="run mode")
    parser.add_argument("--loss_type", type=str, default="smooth_l1", help="loss function")
    parser.add_argument("--save_path", type=str, default="./autodl-tmp", help="output directory")
    parser.add_argument("--use_tensorboard", type=int, default=1, help="enable TensorBoard logging")
    parser.add_argument("--num_workers", type=int, default=4, help="DataLoader num_workers")
    parser.add_argument("--pin_memory", type=int, default=1, help="DataLoader pin_memory")

    # Data
    parser.add_argument("--file_path_d1", type=str, default="./latest_data/data_simplified_basic.json", help="original basic data file path")
    parser.add_argument("--file_path_d2", type=str, default="./latest_data/data_simplified_premix.json", help="original premix data file path")
    parser.add_argument("--file_path_d1_extra", type=str, default="./latest_data/data_simplified_basic_extra.json", help="additional basic data file path")
    parser.add_argument("--file_path_d2_extra", type=str, default="./latest_data/data_simplified_premix_extra.json", help="additional premix data file path")
    parser.add_argument("--personality_path", type=str, default="./merged_v3.json", help="base personality file path")
    parser.add_argument("--personality_path_extra", type=str, default="./merged_v4_L.json", help="additional personality file path")
    parser.add_argument("--load_model_path", type=str, default="./checkpoints/top17", help="checkpoint path")
    
    
    # Model
    parser.add_argument("--d_model", type=int, default=512, help="hidden size")
    parser.add_argument("--nhead", type=int, default=4, help="attention heads")
    parser.add_argument("--n_layer", type=int, default=4, help="number of layers")
    parser.add_argument("--drug_mode", type=int, default=2, help="drug merge mode")
    parser.add_argument("--insulin_mode", type=int, default=1, help="insulin merge mode")
    parser.add_argument("--route_divide", type=int, default=1, help="split route mode")
    parser.add_argument("--use_regimen", type=int, default=0, help="use the insulin regimen representation")
    parser.add_argument("--discharge_gt", type=int, default=1, help="discharge target mode")
    parser.add_argument("--cut_time", type=int, default=15, help="history length cap")
    parser.add_argument("--remove_same_day_pump_subq_mixed", type=int, default=0, help="remove samples that have any stage2 day with both pump and subcutaneous insulin in different slots")
    parser.add_argument("--stage2_max_days", type=int, default=10, help="stage-2 maximum kept days after preprocessing")
    parser.add_argument("--remove_null", type=int, default=1, help="remove low-quality samples")
    parser.add_argument("--stage2_bg_missing_threshold", type=float, default=0.6, help="remove stage2 samples with BG missing ratio above this threshold")
    parser.add_argument("--s2_use_insulin_pump", type=int, default=0, help="whether stage2 keeps insulin-pump patients and merges pump dose into basic slots")
    parser.add_argument("--insulin_transfer_4", type=int, default=1, help="map all stage2 insulin days into a unified four-shot view while keeping regimen flags separate")
    parser.add_argument("--use_c_peptide", type=int, default=0, help="keep normalized C-peptide as separate batch fields for C-peptide experiments")
    parser.add_argument("--personality", type=int, default=1, help="use patient features")
    parser.add_argument("--top_k", type=int, default=17, help="retrieval top-k")
    parser.add_argument("--memory_fusion_temperature", type=float, default=1.0, help="memory fusion temperature")
    parser.add_argument("--memory_mapper_init_gate_logit", type=float, default=-2.0, help="initial gate logit for mapped reference memory residual")
    parser.add_argument("--use_attention_fusion", type=int, default=0, help="use attention fusion")
    parser.add_argument("--fusion_nhead", type=int, default=4, help="fusion attention heads")
    parser.add_argument("--use_retrieval_bias", type=int, default=1, help="use retrieval score bias")

    # Optional modules
    parser.add_argument("--use_length_predictor", type=int, default=0, help="use length predictor")
    parser.add_argument("--lambda_length", type=float, default=0.1, help="length loss weight")

    # Optimization stability
    parser.add_argument("--max_grad_norm", type=float, default=5.0, help="gradient clipping norm")
    parser.add_argument("--use_scheduler", type=int, default=1, help="enable lr scheduler")
    parser.add_argument("--scheduler_type", type=str, default="plateau", choices=["plateau", "cosine"], help="scheduler type")
    parser.add_argument("--scheduler_factor", type=float, default=0.88, help="plateau scheduler decay factor")
    parser.add_argument("--scheduler_patience", type=int, default=10, help="plateau scheduler patience")
    parser.add_argument("--scheduler_min_lr", type=float, default=8e-7, help="minimum learning rate")
    parser.add_argument("--scheduler_threshold", type=float, default=1.5e-4, help="minimum significant val improvement")
    parser.add_argument("--scheduler_cooldown", type=int, default=4, help="plateau scheduler cooldown")
    parser.add_argument("--warmup_epochs", type=int, default=8, help="warmup epochs for cosine schedule")
    parser.add_argument("--lr_change", type=int, default=1, help="enable the learning-rate schedule")
    parser.add_argument("--smooth_l1_beta", type=float, default=2.0, help="Smooth L1 beta")
    parser.add_argument("--per_mask", type=int, default=1, help="mask mode")
    parser.add_argument("--bg_discharge_use", type=int, default=1, help="use discharge prediction in bg branch")

    # Shapes and loss weights
    parser.add_argument("--d_bg", type=int, default=7, help="daily blood glucose dimension")
    parser.add_argument("--d_insulin", type=int, default=5, help="daily insulin dimension")
    parser.add_argument("--d_regimen", type=int, default=2, help="daily regimen condition dimension")
    parser.add_argument("--d_person", type=int, default=40, help="patient feature dimension")
    parser.add_argument("--d_insulin_route_stage", type=int, default=2, help="insulin route stage dimension")
    parser.add_argument("--use_soft_regime_mask_train", type=int, default=1, help="use soft regimen mask during training-time insulin decoding")
    parser.add_argument("--soft_regime_floor_train", type=float, default=0.08, help="small probability floor mixed into training-time regimen mask to avoid single-class collapse")
    parser.add_argument("--max_T1", type=int, default=20, help="stage-1 max length")
    parser.add_argument("--max_seq_len", type=int, default=10, help="stage-2 max length")
    parser.add_argument("--lambda_bg", type=float, default=1.0, help="bg loss weight")
    parser.add_argument("--lambda_insulin", type=float, default=1.0, help="insulin loss weight")
    parser.add_argument("--train_insulin_type_only", type=int, default=0, help="train insulin type classification only")
    parser.add_argument("--train_bg_when_type_only", type=int, default=0, help="still optimize bg branch when training insulin type only")
    parser.add_argument("--dynamic_multi_task_loss", type=int, default=1, help="linearly interpolate multi-task loss weights across training")
    parser.add_argument("--phase1_lambda_bg", type=float, default=0.86, help="phase 1 bg loss weight")
    parser.add_argument("--phase2_lambda_bg", type=float, default=0.78, help="phase 2 bg loss weight")
    parser.add_argument("--phase1_lambda_insulin", type=float, default=1.22, help="phase 1 insulin loss weight")
    parser.add_argument("--phase2_lambda_insulin", type=float, default=1.24, help="phase 2 insulin loss weight")
    parser.add_argument("--lambda_discharge", type=float, default=0.3, help="discharge loss weight")
    parser.add_argument("--insulin_flag_dims", type=int, default=2, help="number of insulin regimen flag dims")
    parser.add_argument("--insulin_type_loss_weight", type=float, default=0.04, help="weight for insulin type classification loss")
    parser.add_argument("--insulin_type_weight_basic", type=float, default=1.05, help="class weight for basic insulin type")
    parser.add_argument("--insulin_type_weight_premix", type=float, default=1.45, help="class weight for premix insulin type")
    parser.add_argument("--insulin_type_weight_none", type=float, default=1.00, help="class weight for none insulin type")
    parser.add_argument("--basic_dose_loss_weight", type=float, default=1.00, help="extra loss weight for basic dose regression")
    parser.add_argument("--premix_dose_loss_weight", type=float, default=1.00, help="extra loss weight for premix dose regression")
    parser.add_argument("--basic_sc_focus_loss_weight", type=float, default=0.00, help="extra regression loss weight applied to Basic-SC slots on ground-truth basic days")
    parser.add_argument("--premix_sc_focus_loss_weight", type=float, default=0.00, help="extra regression loss weight applied to Premix-SC slots on ground-truth premix days")
    parser.add_argument("--premix_recall_focus_loss_weight", type=float, default=0.00, help="extra premix-specific classification loss to improve premix recall")
    parser.add_argument("--insulin_type_label_smoothing", type=float, default=0.02, help="label smoothing used in insulin type classification to reduce single-class collapse")
    parser.add_argument("--pump_dose_weight", type=float, default=1.5, help="extra regression weight for pump-related dose slots")
    parser.add_argument("--iv_dose_weight", type=float, default=2.0, help="extra regression weight for IV dose slot")
    parser.add_argument("--micro_dose_weight", type=float, default=1.2, help="extra regression weight for micro-pump dose slot")
    parser.add_argument("--effective_dose_threshold", type=float, default=2.0, help="clinical threshold below which insulin dose is treated as ineffective")
    parser.add_argument("--rule_stats_path", type=str, default="", help="json summary produced by compute_regimen_ratio_stats.py for rule-based probabilistic inference")
    parser.add_argument("--rule_prior_weight", type=float, default=0.20, help="weight of top-k retrieval prior in rule-based probabilistic inference")
    parser.add_argument("--rule_softmax_temperature", type=float, default=0.25, help="temperature used when converting rule evidence scores to probabilities")
    parser.add_argument("--effective_dose_weight", type=float, default=1.18, help="extra regression weight for target doses above effective threshold")
    parser.add_argument("--effective_presence_loss_weight", type=float, default=0.16, help="penalty weight for predicting below threshold on effective-dose targets")
    parser.add_argument("--inactive_dose_suppress_weight", type=float, default=0.16, help="penalty weight for predicting above threshold on inactive-dose targets")
    parser.add_argument("--insulin_delta_loss_weight", type=float, default=0.60, help="continuous day-to-day insulin dose delta loss weight")
    parser.add_argument("--insulin_delta_change_threshold", type=float, default=1.0, help="absolute dose delta treated as a real adjustment for extra weighting")
    parser.add_argument("--insulin_delta_change_weight", type=float, default=4.0, help="extra weight multiplier on true day-to-day dose adjustments")
    parser.add_argument("--insulin_daily_total_delta_loss_weight", type=float, default=0.30, help="continuous daily total insulin delta loss weight")
    parser.add_argument("--bg_down_insulin_rise_penalty_weight", type=float, default=0.03, help="extra penalty when predicted insulin keeps rising on target segments where bg is already decreasing")
    parser.add_argument("--bg_down_threshold", type=float, default=0.2, help="minimum target bg day-to-day decrease to trigger bg-down insulin-rise penalty")
    parser.add_argument("--target_insulin_nonincrease_margin", type=float, default=0.5, help="target daily-total insulin increase tolerated before disabling bg-down insulin-rise penalty")
    parser.add_argument("--predicted_insulin_rise_margin", type=float, default=0.5, help="predicted daily-total insulin increase tolerated before bg-down insulin-rise penalty activates")
    parser.add_argument("--use_premix_oversample", type=int, default=1, help="oversample sequences containing premix days")
    parser.add_argument("--premix_oversample_weight", type=float, default=1.55, help="sampling weight for sequences containing premix days")
    parser.add_argument("--use_premix_augmentation", type=int, default=1, help="apply light augmentation to premix insulin doses during training")
    parser.add_argument("--premix_aug_prob", type=float, default=0.2, help="probability of augmenting each premix day")
    parser.add_argument("--premix_aug_scale", type=float, default=0.02, help="relative jitter scale for premix dose augmentation")
    parser.add_argument("--metric_positive_threshold", type=float, default=1e-3, help="values below this threshold are treated as zero in event-style metrics")
    parser.add_argument("--tf_ratio", type=float, default=0.9, help="teacher forcing ratio")
    parser.add_argument("--tf_start", type=float, default=0.75, help="initial teacher forcing ratio")
    parser.add_argument("--tf_end", type=float, default=0.05, help="final teacher forcing ratio")
    parser.add_argument("--tf_decay_ratio", type=float, default=0.30, help="fraction of epochs used to decay tf ratio")
    parser.add_argument("--teacher_forcing_mode", type=str, default="prefix", help="teacher forcing schedule mode: prefix or stepwise")
    parser.add_argument("--use_two_stage_curriculum", type=int, default=1, help="use two-stage loss curriculum for insulin tasks")
    parser.add_argument("--two_stage_phase1_ratio", type=float, default=0.10, help="fraction of total epochs used for phase 1")
    parser.add_argument("--phase1_insulin_type_loss_weight", type=float, default=0.08, help="phase 1 insulin type loss weight")
    parser.add_argument("--phase1_premix_recall_focus_loss_weight", type=float, default=0.00, help="phase 1 premix recall focus loss weight")
    parser.add_argument("--phase1_basic_sc_focus_loss_weight", type=float, default=0.00, help="phase 1 basic sc focus loss weight")
    parser.add_argument("--phase1_premix_sc_focus_loss_weight", type=float, default=0.00, help="phase 1 premix sc focus loss weight")
    parser.add_argument("--phase2_insulin_type_loss_weight", type=float, default=0.04, help="phase 2 insulin type loss weight")
    parser.add_argument("--phase2_premix_recall_focus_loss_weight", type=float, default=0.00, help="phase 2 premix recall focus loss weight")
    parser.add_argument("--phase2_basic_sc_focus_loss_weight", type=float, default=0.00, help="phase 2 basic sc focus loss weight")
    parser.add_argument("--phase2_premix_sc_focus_loss_weight", type=float, default=0.00, help="phase 2 premix sc focus loss weight")
    parser.add_argument("--insulin_regression_loss_weight", type=float, default=1.16, help="global multiplier for insulin regression losses inside CombinedLoss")
    parser.add_argument("--phase1_insulin_regression_loss_weight", type=float, default=1.18, help="phase 1 multiplier for insulin regression losses")
    parser.add_argument("--phase2_insulin_regression_loss_weight", type=float, default=1.20, help="phase 2 multiplier for insulin regression losses")
    parser.add_argument("--selection_warmup_epochs", type=int, default=0, help="do not update best checkpoint before this epoch")
    parser.add_argument("--selection_raw_sc_weight", type=float, default=0.5, help="selection weight for BG+Basic-SC+Premix-SC sum")
    parser.add_argument("--selection_merged_bg_weight", type=float, default=0.5, help="selection weight for merged+BG MAE sum")
    parser.add_argument("--selection_flag_penalty_basic_weight", type=float, default=0.00, help="selection penalty weight for wrong basic flag")
    parser.add_argument("--selection_flag_penalty_premix_weight", type=float, default=0.00, help="selection penalty weight for wrong premix flag")
    parser.add_argument("--selection_flag_penalty_none_weight", type=float, default=0.00, help="selection penalty weight for wrong none flag")
    parser.add_argument("--selection_premix_recall_floor", type=float, default=0.00, help="desired minimum premix recall for checkpoint selection")
    parser.add_argument("--selection_premix_recall_penalty_weight", type=float, default=0.00, help="extra selection penalty when premix recall stays below the desired floor")
    parser.add_argument("--bg_min_value", type=float, default=2.0, help="minimum bg prediction")
    parser.add_argument("--bg_max_value", type=float, default=35.0, help="maximum bg prediction")
    parser.add_argument("--insulin_min_value", type=float, default=0.0, help="minimum insulin prediction")
    parser.add_argument("--insulin_max_value", type=float, default=55.0, help="maximum insulin prediction")

    # Early stopping
    parser.add_argument("--use_early_stop", type=int, default=0, help="enable early stopping")
    parser.add_argument("--early_stop_patience", type=int, default=300, help="early stopping patience")
    parser.add_argument("--early_stop_min_delta", type=float, default=1e-4, help="minimum meaningful val improvement")
    parser.add_argument("--stop_on_min_lr", type=int, default=0, help="stop if lr sits at min_lr with no progress")
    parser.add_argument("--min_lr_patience", type=int, default=80, help="patience after reaching min lr")

    # Architecture refinements
    parser.add_argument("--dropout", type=float, default=0.1, help="dropout")
    parser.add_argument("--d_ff", type=int, default=0, help="ffn hidden dim; 0 means 4 * d_model")
    parser.add_argument("--person_nhead", type=int, default=4, help="personalization attention heads")
    parser.add_argument("--use_person_self_attention", type=int, default=0, help="enable feature-level self-attention in personal encoding")
    parser.add_argument("--residual_output_mix_init_logit", type=float, default=0.0, help="initial residual-vs-absolute output blend logit")
    parser.add_argument("--bg_reference_prior_mix_init_logit", type=float, default=-1.5, help="initial BG raw-reference prior blend logit")
    parser.add_argument("--insulin_reference_prior_mix_init_logit", type=float, default=-1.4, help="initial insulin raw-reference prior blend logit")
    parser.add_argument("--regimen_context_gate_init_logit", type=float, default=-2.0, help="initial gate logit for weak regimen context injection into unified insulin decoding")
    parser.add_argument("--bg_reference_dynamic_logit_scale", type=float, default=0.35, help="max additional dynamic correction logit magnitude for BG reference guidance")
    parser.add_argument("--insulin_reference_dynamic_logit_scale", type=float, default=0.08, help="max additional dynamic correction logit magnitude for insulin reference guidance")
    parser.add_argument("--bg_residual_delta_scale", type=float, default=6.0, help="max BG residual delta scale per autoregressive step")
    parser.add_argument("--insulin_residual_delta_scale", type=float, default=16.0, help="max insulin residual delta scale per autoregressive step")

    # Loss refinements
    parser.add_argument("--diversity_alpha", type=float, default=0.0, help="diversity regularization weight")
    parser.add_argument("--sparsity_beta", type=float, default=0.0, help="sparsity regularization weight")
    parser.add_argument("--use_contrastive", type=int, default=0, help="use contrastive loss")
    parser.add_argument("--contrast_temp", type=float, default=0.5, help="contrastive temperature")
    parser.add_argument("--use_focal", type=int, default=0, help="use focal loss")
    parser.add_argument("--focal_alpha", type=float, default=0.25, help="focal alpha")
    parser.add_argument("--focal_gamma", type=float, default=2.0, help="focal gamma")
    parser.add_argument("--w_base", type=float, default=1.0, help="base loss weight")
    parser.add_argument("--w_contrast", type=float, default=0.05, help="contrastive loss weight")
    parser.add_argument("--w_focal", type=float, default=0.1, help="focal loss weight")

    args = parser.parse_args()

    if args.d_ff == 0:
        args.d_ff = args.d_model * 4

    return args
