# -*- encoding: utf-8 -*-
"""
Training configuration for the diabetes two-stage model.
"""
import argparse
import torch


def opt_config():
    parser = argparse.ArgumentParser(description="Diabetes-two-stage")

    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu", help="device")
    parser.add_argument("--seed", type=int, default=42, help="random seed")
    parser.add_argument("--split_seed", type=int, default=0, help="random seed used only for dataset shuffling/splitting")
    parser.add_argument("--test_only", type=int, default=0, help="load model only without training")

    # Training
    parser.add_argument("--lr", type=float, default=1e-4, help="base learning rate")
    parser.add_argument("--optimizer", type=str, default="adamw", choices=["adam", "adamw"], help="optimizer type")
    parser.add_argument("--weight_decay", type=float, default=3e-4, help="weight decay")
    parser.add_argument("--batch_size", type=int, default=64, help="batch size")
    parser.add_argument("--epochs", type=int, default=1000, help="max training epochs")
    parser.add_argument("--mode", type=str, default="train", help="run mode")
    parser.add_argument("--loss_type", type=str, default="smooth_l1", help="loss function")
    parser.add_argument("--save_path", type=str, default="./autodl-tmp", help="output directory")
    parser.add_argument("--use_tensorboard", type=int, default=1, help="enable TensorBoard logging")
    parser.add_argument("--num_workers", type=int, default=4, help="DataLoader num_workers")
    parser.add_argument("--pin_memory", type=int, default=1, help="DataLoader pin_memory")

    # Data
    parser.add_argument("--file_path_d1", type=str, default="./latest_data/data_simplified_basic.json", help="original basic data file path")
    parser.add_argument("--file_path_d2", type=str, default="./latest_data/data_simplified_premix.json", help="original premix data file path")
    parser.add_argument("--file_path_d1_extra", type=str, default="./latest_data/data_simplified_basic_extra.json", help="additional basic data file path")
    parser.add_argument("--file_path_d2_extra", type=str, default="./latest_data/data_simplified_premix_extra.json", help="additional premix data file path")
    parser.add_argument("--personality_path", type=str, default="./merged_v3.json", help="base personality file path")
    parser.add_argument("--personality_path_extra", type=str, default="./merged_v4_L.json", help="additional personality file path")
    parser.add_argument("--enable_zero_day_case_filter", type=int, default=1, help="remove cases with any day of all-zero non-IV/non-micro insulin")
    parser.add_argument("--enable_excluded_case_filter", type=int, default=1, help="remove cases listed in excluded_case_ids")
    parser.add_argument("--load_model_path", type=str, default="./checkpoints/topk10", help="checkpoint path")

    # Model
    parser.add_argument("--d_model", type=int, default=512, help="hidden size")
    parser.add_argument("--nhead", type=int, default=4, help="attention heads")
    parser.add_argument("--n_layer", type=int, default=4, help="number of layers")
    parser.add_argument("--drug_mode", type=int, default=2, help="drug merge mode")
    parser.add_argument("--insulin_mode", type=int, default=1, help="insulin merge mode")
    parser.add_argument("--route_divide", type=int, default=1, help="split route mode")
    parser.add_argument("--use_regimen", type=int, default=1, help="use the simplified insulin representation")
    parser.add_argument("--discharge_gt", type=int, default=1, help="discharge target mode")
    parser.add_argument("--cut_time", type=int, default=7, help="keep samples with stay length <= cut_time; 0 disables")
    parser.add_argument("--stage2_max_days", type=int, default=10, help="maximum stage-2 days kept when stage-2 history is loaded")
    parser.add_argument("--remove_null", type=int, default=1, help="remove low-quality samples")
    parser.add_argument("--personality", type=int, default=1, help="use patient features")
    parser.add_argument("--top_k", type=int, default=10, help="retrieval top-k")
    parser.add_argument("--memory_fusion_temperature", type=float, default=1.0, help="memory fusion temperature")
    parser.add_argument("--memory_mapper_init_gate_logit", type=float, default=-2.0, help="initial gate logit for mapped reference memory residual")
    parser.add_argument("--use_attention_fusion", type=int, default=0, help="use attention fusion")
    parser.add_argument("--fusion_nhead", type=int, default=4, help="fusion attention heads")
    parser.add_argument("--use_retrieval_bias", type=int, default=1, help="use retrieval score bias")

    # Optional modules
    parser.add_argument("--use_length_predictor", type=int, default=0, help="use length predictor")
    parser.add_argument("--lambda_length", type=float, default=0.1, help="length loss weight")

    # Optimization stability
    parser.add_argument("--max_grad_norm", type=float, default=5.0, help="gradient clipping norm")
    parser.add_argument("--use_scheduler", type=int, default=1, help="enable lr scheduler")
    parser.add_argument("--scheduler_type", type=str, default="plateau", choices=["plateau", "cosine"], help="scheduler type")
    parser.add_argument("--scheduler_factor", type=float, default=0.8, help="plateau scheduler decay factor")
    parser.add_argument("--scheduler_patience", type=int, default=8, help="plateau scheduler patience")
    parser.add_argument("--scheduler_min_lr", type=float, default=1e-7, help="minimum learning rate")
    parser.add_argument("--scheduler_threshold", type=float, default=1e-3, help="minimum significant val improvement")
    parser.add_argument("--scheduler_cooldown", type=int, default=2, help="plateau scheduler cooldown")
    parser.add_argument("--warmup_epochs", type=int, default=5, help="warmup epochs for cosine schedule")
    parser.add_argument("--lr_change", type=int, default=1, help="enable the learning-rate schedule")
    parser.add_argument("--smooth_l1_beta", type=float, default=5.0, help="Smooth L1 beta")
    parser.add_argument("--per_mask", type=int, default=1, help="mask mode")
    parser.add_argument("--bg_discharge_use", type=int, default=1, help="use discharge prediction in bg branch")

    # Shapes and loss weights
    parser.add_argument("--d_bg", type=int, default=7, help="daily blood glucose dimension")
    parser.add_argument("--d_insulin", type=int, default=6, help="daily insulin dimension")
    parser.add_argument("--d_drug", type=int, default=17, help="daily non-insulin drug dimension")
    parser.add_argument("--d_person", type=int, default=40, help="patient feature dimension")
    parser.add_argument("--d_insulin_route_stage", type=int, default=2, help="insulin route stage dimension")
    parser.add_argument("--max_T1", type=int, default=7, help="stage-1 max length")
    parser.add_argument("--max_seq_len", type=int, default=None, help="decoder max length; defaults to max_T1")
    parser.add_argument("--lambda_bg", type=float, default=0.9, help="bg loss weight")
    parser.add_argument("--lambda_insulin", type=float, default=1.0, help="insulin loss weight")
    parser.add_argument("--lambda_discharge", type=float, default=0.3, help="discharge loss weight")
    parser.add_argument("--insulin_flag_dims", type=int, default=0, help="number of insulin regimen flag dims")
    parser.add_argument("--insulin_type_loss_weight", type=float, default=0.0, help="weight for insulin type classification loss")
    parser.add_argument("--insulin_type_weight_basic", type=float, default=1.0, help="class weight for basic insulin type")
    parser.add_argument("--insulin_type_weight_premix", type=float, default=1.0, help="class weight for premix insulin type")
    parser.add_argument("--insulin_type_weight_none", type=float, default=1.0, help="class weight for none insulin type")
    parser.add_argument("--premix_dose_loss_weight", type=float, default=1.0, help="extra loss weight for premix dose regression")
    parser.add_argument("--basic_sc_focus_loss_weight", type=float, default=0.0, help="extra regression loss weight applied to Basic-SC slots on ground-truth basic days")
    parser.add_argument("--basic_merged_focus_loss_weight", type=float, default=0.0, help="extra regression loss weight applied to Basic-Merged slots on non-premix days")
    parser.add_argument("--premix_sc_focus_loss_weight", type=float, default=0.0, help="extra regression loss weight applied to Premix-SC slots on ground-truth premix days")
    parser.add_argument("--premix_recall_focus_loss_weight", type=float, default=0.0, help="extra premix-specific classification loss to improve premix recall")
    parser.add_argument("--pump_dose_weight", type=float, default=1.0, help="extra regression weight for pump-related dose slots")
    parser.add_argument("--iv_dose_weight", type=float, default=0.7, help="extra regression weight for IV dose slot")
    parser.add_argument("--micro_dose_weight", type=float, default=0.7, help="extra regression weight for micro-pump dose slot")
    parser.add_argument("--effective_dose_threshold", type=float, default=1.5, help="clinical threshold below which insulin dose is treated as ineffective")
    parser.add_argument("--effective_dose_weight", type=float, default=2.0, help="extra regression weight for target doses above effective threshold")
    parser.add_argument("--effective_presence_loss_weight", type=float, default=0.0, help="penalty weight for predicting below threshold on effective-dose targets")
    parser.add_argument("--inactive_dose_suppress_weight", type=float, default=0.08, help="penalty weight for predicting above threshold on inactive-dose targets")
    parser.add_argument("--insulin_delta_loss_weight", type=float, default=0.60, help="continuous day-to-day insulin dose delta loss weight")
    parser.add_argument("--insulin_delta_change_threshold", type=float, default=1.0, help="absolute dose delta treated as a real adjustment for extra weighting")
    parser.add_argument("--insulin_delta_change_weight", type=float, default=4.0, help="extra weight multiplier on true day-to-day dose adjustments")
    parser.add_argument("--insulin_daily_total_delta_loss_weight", type=float, default=0.30, help="continuous daily total insulin delta loss weight")
    parser.add_argument("--bg_down_insulin_rise_penalty_weight", type=float, default=0.65, help="extra penalty when predicted insulin keeps rising on target segments where bg is already decreasing")
    parser.add_argument("--bg_down_threshold", type=float, default=0.15, help="minimum target bg day-to-day decrease to trigger bg-down insulin-rise penalty")
    parser.add_argument("--target_insulin_nonincrease_margin", type=float, default=0.20, help="target daily-total insulin increase tolerated before disabling bg-down insulin-rise penalty")
    parser.add_argument("--predicted_insulin_rise_margin", type=float, default=0.10, help="predicted daily-total insulin increase tolerated before bg-down insulin-rise penalty activates")
    parser.add_argument("--use_premix_oversample", type=int, default=0, help="oversample sequences containing premix days")
    parser.add_argument("--premix_oversample_weight", type=float, default=2.0, help="sampling weight for sequences containing premix days")
    parser.add_argument("--use_high_bg_oversample", type=int, default=0, help="oversample sequences containing high-bg targets")
    parser.add_argument("--high_bg_oversample_weight", type=float, default=2.2, help="sampling weight for sequences containing high-bg targets")
    parser.add_argument("--bg_delta_loss_weight", type=float, default=0.30, help="extra temporal-delta loss weight for BG regression")
    parser.add_argument("--bg_pattern_loss_weight", type=float, default=0.0, help="extra within-day BG pattern loss weight")
    parser.add_argument("--use_premix_augmentation", type=int, default=0, help="apply light augmentation to premix insulin doses during training")
    parser.add_argument("--premix_aug_prob", type=float, default=0.2, help="probability of augmenting each premix day")
    parser.add_argument("--premix_aug_scale", type=float, default=0.03, help="relative jitter scale for premix dose augmentation")
    parser.add_argument("--metric_positive_threshold", type=float, default=1e-3, help="values below this threshold are treated as zero in event-style metrics")
    parser.add_argument("--tf_ratio", type=float, default=0.9, help="teacher forcing ratio")
    parser.add_argument("--tf_start", type=float, default=0.9, help="initial teacher forcing ratio")
    parser.add_argument("--tf_end", type=float, default=0.0, help="final teacher forcing ratio")
    parser.add_argument("--tf_decay_ratio", type=float, default=0.5, help="fraction of epochs used to decay tf ratio")
    parser.add_argument("--teacher_forcing_mode", type=str, default="prefix", help="teacher forcing schedule mode: prefix or stepwise")
    parser.add_argument("--use_two_stage_curriculum", type=int, default=0, help="use two-stage loss curriculum for insulin tasks")
    parser.add_argument("--two_stage_phase1_ratio", type=float, default=0.12, help="fraction of total epochs used for phase 1")
    parser.add_argument("--phase1_insulin_type_loss_weight", type=float, default=0.0, help="phase 1 insulin type loss weight")
    parser.add_argument("--phase1_premix_recall_focus_loss_weight", type=float, default=0.0, help="phase 1 premix recall focus loss weight")
    parser.add_argument("--phase1_basic_sc_focus_loss_weight", type=float, default=0.0, help="phase 1 basic sc focus loss weight")
    parser.add_argument("--phase1_premix_sc_focus_loss_weight", type=float, default=0.0, help="phase 1 premix sc focus loss weight")
    parser.add_argument("--phase2_insulin_type_loss_weight", type=float, default=0.0, help="phase 2 insulin type loss weight")
    parser.add_argument("--phase2_premix_recall_focus_loss_weight", type=float, default=0.0, help="phase 2 premix recall focus loss weight")
    parser.add_argument("--phase2_basic_sc_focus_loss_weight", type=float, default=0.0, help="phase 2 basic sc focus loss weight")
    parser.add_argument("--phase2_premix_sc_focus_loss_weight", type=float, default=0.0, help="phase 2 premix sc focus loss weight")
    parser.add_argument("--bg_min_value", type=float, default=2.0, help="minimum bg prediction")
    parser.add_argument("--bg_max_value", type=float, default=35.0, help="maximum bg prediction")
    parser.add_argument("--high_bg_threshold", type=float, default=10.0, help="target bg threshold for extra high-bg regression focus")
    parser.add_argument("--high_bg_focus_loss_weight", type=float, default=0.0, help="extra regression loss weight on high-bg targets")
    parser.add_argument("--bg_underpredict_loss_weight", type=float, default=0.0, help="extra penalty for underpredicting BG targets")
    parser.add_argument("--high_bg_underpredict_extra_weight", type=float, default=1.5, help="extra multiplier for underprediction penalty on high-BG targets")
    parser.add_argument("--insulin_min_value", type=float, default=0.0, help="minimum insulin prediction")
    parser.add_argument("--insulin_max_value", type=float, default=50.0, help="default maximum insulin prediction for non-micro-pump slots")
    parser.add_argument("--insulin_micro_pump_max_value", type=float, default=200.0, help="maximum insulin prediction for micro-pump slot")
    parser.add_argument("--insulin_micro_pump_index", type=int, default=4, help="full insulin-vector index of the micro-pump slot")

    # Early stopping
    parser.add_argument("--use_early_stop", type=int, default=0, help="enable early stopping")
    parser.add_argument("--early_stop_patience", type=int, default=30, help="early stopping patience")
    parser.add_argument("--early_stop_min_delta", type=float, default=1e-4, help="minimum meaningful val improvement")
    parser.add_argument("--early_stop_start_epoch", type=int, default=200, help="do not activate early stopping before this epoch")
    parser.add_argument("--stop_on_min_lr", type=int, default=0, help="stop if lr sits at min_lr with no progress")
    parser.add_argument("--min_lr_patience", type=int, default=30, help="patience after reaching min lr")

    # Architecture refinements
    parser.add_argument("--dropout", type=float, default=0.1, help="dropout")
    parser.add_argument("--d_ff", type=int, default=0, help="ffn hidden dim; 0 means 4 * d_model")
    parser.add_argument("--person_nhead", type=int, default=4, help="personalization attention heads")
    parser.add_argument("--use_person_self_attention", type=int, default=0, help="enable feature-level self-attention in personal encoding")
    parser.add_argument("--residual_output_mix_init_logit", type=float, default=0.0, help="initial residual-vs-absolute output blend logit")
    parser.add_argument("--bg_reference_prior_mix_init_logit", type=float, default=-1.0, help="initial BG raw-reference prior blend logit")
    parser.add_argument("--insulin_reference_prior_mix_init_logit", type=float, default=-1.5, help="initial insulin raw-reference prior blend logit")
    parser.add_argument("--bg_reference_dynamic_logit_scale", type=float, default=0.35, help="max additional dynamic correction logit magnitude for BG reference guidance")
    parser.add_argument("--insulin_reference_dynamic_logit_scale", type=float, default=0.15, help="max additional dynamic correction logit magnitude for insulin reference guidance")
    parser.add_argument("--bg_residual_delta_scale", type=float, default=6.0, help="max BG residual delta scale per autoregressive step")
    parser.add_argument("--insulin_residual_delta_scale", type=float, default=30.0, help="max insulin residual delta scale per autoregressive step")
    parser.add_argument("--rare_route_init_logit", type=float, default=-2.2, help="initial gate logit for rare insulin routes such as IV and micro-pump")
    parser.add_argument("--rare_route_reference_prior_scale", type=float, default=0.15, help="relative prior-mix scale applied to rare insulin routes")
    parser.add_argument("--rare_route_activity_boost", type=float, default=1.0, help="logit boost when previous/reference rare-route activity is already present")
    parser.add_argument("--ketosis_feature_index", type=int, default=66, help="person feature index for complications-酮症")
    parser.add_argument("--dka_feature_index", type=int, default=67, help="person feature index for complications-酮症酸中毒")
    parser.add_argument("--hhs_feature_index", type=int, default=68, help="person feature index for complications-高渗高血糖综合征")
    parser.add_argument("--rare_route_emergency_boost", type=float, default=1.5, help="extra rare-route gate logit boost from emergency-condition features")

    # Loss refinements
    parser.add_argument("--diversity_alpha", type=float, default=0.001, help="diversity regularization weight")
    parser.add_argument("--sparsity_beta", type=float, default=0.005, help="sparsity regularization weight")
    parser.add_argument("--use_contrastive", type=int, default=0, help="use contrastive loss")
    parser.add_argument("--contrast_temp", type=float, default=0.5, help="contrastive temperature")
    parser.add_argument("--use_focal", type=int, default=0, help="use focal loss")
    parser.add_argument("--focal_alpha", type=float, default=0.25, help="focal alpha")
    parser.add_argument("--focal_gamma", type=float, default=2.0, help="focal gamma")
    parser.add_argument("--w_base", type=float, default=1.0, help="base loss weight")
    parser.add_argument("--w_contrast", type=float, default=0.05, help="contrastive loss weight")
    parser.add_argument("--w_focal", type=float, default=0.1, help="focal loss weight")

    args = parser.parse_args()

    if args.d_ff == 0:
        args.d_ff = args.d_model * 4

    if args.max_seq_len is None:
        args.max_seq_len = args.max_T1

    return args
